# Generated by Django 4.2.24 on 2025-09-24 05:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sketch',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='sketches/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
