# Generated by Django 4.2.24 on 2025-09-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sketch', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sketch',
            old_name='sketch_file',
            new_name='file',
        ),
    ]
