# Generated by Django 4.2.24 on 2025-09-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketch', '0003_rename_sketch_file_sketch_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
