# Generated by Django 4.2.24 on 2025-09-12 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sketch', '0004_sketch_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sketches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='file',
            field=models.FileField(upload_to='upload/sketches/'),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
