# Generated by Django 4.2.24 on 2025-09-17 10:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_basemodel_creator"),
        ("converter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionResult",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                ("dsl_output", models.JSONField(help_text="DSL输出结果")),
                ("html_output", models.TextField(blank=True, help_text="HTML预览输出")),
                (
                    "token_report",
                    models.JSONField(default=dict, help_text="令牌使用报告"),
                ),
            ],
            options={
                "verbose_name": "转换结果",
                "verbose_name_plural": "转换结果",
            },
            bases=("core.basemodel",),
        ),
        migrations.CreateModel(
            name="ConversionTask",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                ("name", models.CharField(help_text="任务名称", max_length=200)),
                (
                    "input_file",
                    models.FileField(
                        help_text="输入的设计文件", upload_to="conversion_inputs/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        help_text="任务状态",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, help_text="转换进度 (0-100)"),
                ),
                ("error_message", models.TextField(blank=True, help_text="错误信息")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, help_text="开始时间", null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="完成时间", null=True),
                ),
            ],
            options={
                "verbose_name": "转换任务",
                "verbose_name_plural": "转换任务",
                "ordering": ["-created_time"],
            },
            bases=("core.basemodel",),
        ),
        migrations.CreateModel(
            name="DesignTokens",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                ("name", models.CharField(help_text="令牌配置名称", max_length=100)),
                (
                    "file",
                    models.FileField(
                        help_text="设计令牌JSON文件",
                        upload_to="design_tokens/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["json"])
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "设计令牌",
                "verbose_name_plural": "设计令牌",
            },
            bases=("core.basemodel",),
        ),
        migrations.DeleteModel(
            name="Converter",
        ),
        migrations.AddField(
            model_name="conversiontask",
            name="design_tokens",
            field=models.ForeignKey(
                blank=True,
                help_text="使用的设计令牌",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="converter.designtokens",
            ),
        ),
        migrations.AddField(
            model_name="conversionresult",
            name="task",
            field=models.OneToOneField(
                help_text="关联的转换任务",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result",
                to="converter.conversiontask",
            ),
        ),
    ]
