# Generated by Django 4.2.24 on 2025-09-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversiontask',
            name='source_type',
            field=models.CharField(choices=[('sketch', 'Sketch'), ('figma', 'Figma')], default='sketch', help_text='设计源类型', max_length=20),
        ),
        migrations.AddField(
            model_name='conversiontask',
            name='source_url',
            field=models.URLField(blank=True, help_text='设计源URL (例如 Figma 链接)', null=True),
        ),
        migrations.AlterField(
            model_name='conversiontask',
            name='input_file',
            field=models.FileField(blank=True, help_text='输入的设计文件 (例如 Sketch 文件)', null=True, upload_to='conversion_inputs/'),
        ),
    ]
