# Generated by Django 4.2.24 on 2025-09-24 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designtokens',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversiontask',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversiontask',
            name='design_tokens',
            field=models.ForeignKey(blank=True, help_text='使用的设计令牌', null=True, on_delete=django.db.models.deletion.SET_NULL, to='converter.designtokens'),
        ),
        migrations.AddField(
            model_name='conversionresult',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversionresult',
            name='task',
            field=models.OneToOneField(help_text='关联的转换任务', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='converter.conversiontask'),
        ),
    ]
