# Generated by Django 4.2.24 on 2025-09-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionresult',
            name='llm_usage',
            field=models.JSONField(default=dict, help_text='LLM token 用量汇总'),
        ),
    ]
