# Generated by Django 4.2.24 on 2025-09-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversiontask',
            name='handled_nodes',
            field=models.IntegerField(default=0, help_text='已处理的节点数'),
        ),
        migrations.AlterField(
            model_name='conversiontask',
            name='hidden_nodes',
            field=models.IntegerField(default=0, help_text='隐藏的的节点数'),
        ),
    ]
