# Generated by Django 4.2.24 on 2025-09-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_conversiontask_source_type_conversiontask_source_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversionresult',
            name='html_output',
        ),
        migrations.AddField(
            model_name='conversionresult',
            name='project_download_path',
            field=models.CharField(blank=True, help_text='生成的前端项目压缩包存储路径', max_length=1024, null=True),
        ),
    ]
