# Generated by Django 4.2.24 on 2025-09-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_alter_conversiontask_handled_nodes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversiontask',
            name='phase',
            field=models.CharField(choices=[('pending', '待开始'), ('dsl_conversion', 'DSL 转换'), ('frontend_generation', '前端生成'), ('completed', '已完成')], default='pending', help_text='任务所处阶段', max_length=32),
        ),
    ]
