
# Sketch Layer Types
LAYER_PAGE = "page"
LAYER_ARTBOARD = "artboard"
LAYER_GROUP = "group"
LAYER_SYMBOL_MASTER = "symbolMaster"
LAYER_SYMBOL_INSTANCE = "symbolInstance"
LAYER_TEXT = "text"
LAYER_RECTANGLE = "rectangle"
LAYER_OVAL = "oval"
LAYER_SHAPE_PATH = "shapePath"
LAYER_SHAPE_GROUP = "shapeGroup"
LAYER_BITMAP = "bitmap"
LAYER_TRIANGLE = "triangle"

# DSL Node Types
NODE_PAGE = "page"
NODE_ARTBOARD = "artboard"
NODE_GROUP = "div"
NODE_SYMBOL_MASTER = "symbolMaster"
NODE_SYMBOL_INSTANCE = "symbolInstance"
NODE_TEXT = "text"
NODE_RECTANGLE = "div"
NODE_OVAL = "div"
NODE_SHAPE_PATH = "shapePath"
NODE_SHAPE_GROUP = "shapeGroup"
NODE_BITMAP = "bitmap"
NODE_TRIANGLE = "triangle"
NODE_UNKNOWN_COMPONENT = "UnknownComponent"
NODE_IMAGE = "img"

# Layout Types
LAYOUT_ABSOLUTE = "absolute"
LAYOUT_FLEX = "flex"
LAYOUT_GRID = "grid"
LAYOUT_DIR_ROW = "row"
LAYOUT_DIR_COLUMN = "column"
